GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/618f648c3798510073f842b5

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "A monkey",
    "subscribedToChannel": "The Lads?"
}

###

DELETE http://localhost:3000/subscribers/618f648c3798510073f842b5

###

PATCH http://localhost:3000/subscribers/618f672cb6ee317b2ca4480a
Content-Type: application/json

{
    "name": "New Name"
}